services:
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:management
    ports:
      - 4004:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always

