services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=codimd_password
      - POSTGRES_DB=codimd
    volumes:
      - "codimd-database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:latest
    environment:
      - CMD_DB_URL=postgres://codimd:codimd_password@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "4001:3000"
    volumes:
      - codimd-upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  codimd-database-data: {}
  codimd-upload-data: {}
