services:
  redis:
    container_name: sentry-redis-server
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - sentry-redis:/data

  postgres:
    container_name: sentry-postgres-server
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - sentry-postgres:/var/lib/postgresql


  sentry-web:
    container_name: sentry-web
    image: sentry:latest
    ports:
      - 4005:9000
    depends_on:
      - redis
      - postgres
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${POSTGRES_USER}
      SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_REDIS_HOST: redis

  sentry-worker:
    container_name: sentry-worker
    image: sentry:latest
    depends_on:
      - sentry-web
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${POSTGRES_USER}
      SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_REDIS_HOST: redis
    command: ["sentry", "run", "worker"]


  sentry-corn:
    container_name: sentry-corn
    image: sentry:latest
    depends_on:
      - sentry-web
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${POSTGRES_USER}
      SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_REDIS_HOST: redis
    command: ["sentry", "run", "cron"]



volumes:
  sentry-postgres: {}
  sentry-redis: {}

