services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    mem_limit: 2GB
    ports:
      - 9200:9200
    volumes:
      - elastic_data:/usr/share/elasticsearch
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.1.5
    ports:
      - 5601:5601
    depends_on:
      - elastic
    volumes:
      - kibana_data:/usr/share/kibana
    networks:
      - elastic

networks:
  elastic:

volumes:
  elastic_data:
  kibana_data:
